import { INodeProperties } from 'n8n-workflow';

export const campaignOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['campaign'] } },
    options: [
      { name: 'Create', value: 'create', description: 'Create a new email campaign', action: 'Create a campaign' },
      { name: 'Get All', value: 'getAll', description: 'Get all campaigns', action: 'Get all campaigns' },
      { name: 'Get Basic Info', value: 'getBasicInfo', description: 'Get basic information about a campaign', action: 'Get basic info of a campaign' },
      { name: 'Get By ISP', value: 'getByIsp', description: 'Get campaign statistics grouped by ISP', action: 'Get campaign stats by ISP' },
      { name: 'Get Clicks', value: 'getClicks', description: 'Get click statistics for a campaign', action: 'Get campaign clicks' },
      { name: 'Get Links', value: 'getLinks', description: 'Get all URLs included in a campaign', action: 'Get campaign links' },
      { name: 'Get Openers', value: 'getOpeners', description: 'Get list of subscribers who opened a campaign', action: 'Get campaign openers' },
      { name: 'Get Openers By Browser', value: 'getOpenersByBrowser', description: 'Get opens grouped by browser', action: 'Get campaign openers by browser' },
      { name: 'Get Openers By Country', value: 'getOpenersByCountry', description: 'Get opens grouped by country', action: 'Get campaign openers by country' },
      { name: 'Get Openers By OS', value: 'getOpenersByOs', description: 'Get opens grouped by operating system', action: 'Get campaign openers by OS' },
      { name: 'Get Soft Bounces', value: 'getSoftBounces', description: 'Get soft bounce list for a campaign', action: 'Get campaign soft bounces' },
      { name: 'Get Stats By Date', value: 'getStatsByDate', description: 'Get daily statistics for a list in a date range', action: 'Get campaign stats by date' },
      { name: 'Get Total Info', value: 'getTotalInfo', description: 'Get full statistics for a campaign', action: 'Get campaign total info' },
    ],
    default: 'getAll',
  },
];

const campaignIdOps = [
  'getBasicInfo', 'getTotalInfo', 'getClicks', 'getOpeners',
  'getOpenersByBrowser', 'getOpenersByOs', 'getOpenersByCountry',
  'getSoftBounces', 'getByIsp', 'getLinks',
];

export const campaignFields: INodeProperties[] = [
  {
    displayName: 'Campaign ID',
    name: 'campaignId',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['campaign'], operation: campaignIdOps } },
    default: '',
    description: 'ID of the campaign',
  },
  {
    displayName: 'Name',
    name: 'name',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['campaign'], operation: ['create'] } },
    default: '',
    description: 'Internal name of the campaign',
  },
  {
    displayName: 'Subject',
    name: 'subject',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['campaign'], operation: ['create'] } },
    default: '',
    description: 'Email subject line that recipients will see',
  },
  {
    displayName: 'Content (HTML)',
    name: 'content',
    type: 'string',
    required: true,
    typeOptions: { rows: 5 },
    displayOptions: { show: { resource: ['campaign'], operation: ['create'] } },
    default: '',
    description: 'HTML body of the campaign. Must include *|UNSUBSCRIBE_URL|* placeholder.',
  },
  {
    displayName: 'List IDs',
    name: 'listIds',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['campaign'], operation: ['create'] } },
    default: '',
    description: 'Comma-separated list of mailing list IDs to send this campaign to',
  },
  {
    displayName: 'From Email',
    name: 'fromEmail',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['campaign'], operation: ['create'] } },
    default: '',
    placeholder: 'sender@example.com',
    description: 'Sender email address',
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    displayOptions: { show: { resource: ['campaign'], operation: ['create'] } },
    default: {},
    options: [
      { displayName: 'From Name', name: 'from_name', type: 'string', default: '', description: 'Sender name displayed in the From field' },
      { displayName: 'Schedule Date', name: 'date_send', type: 'dateTime', default: '', description: 'Schedule the campaign for a future date/time (format: YYYY-MM-DD HH:MM)' },
      { displayName: 'Tracking Enabled', name: 'tracking_urls', type: 'boolean', default: true, description: 'Whether to enable click and open tracking' },
      { displayName: 'Tracking Domain', name: 'tracking_domain', type: 'string', default: '', description: 'Custom domain to use for tracking links' },
      { displayName: 'Use HTTPS', name: 'https', type: 'boolean', default: true, description: 'Whether to use HTTPS for tracking links' },
    ],
  },
  {
    displayName: 'List ID',
    name: 'statsByDateListId',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['campaign'], operation: ['getStatsByDate'] } },
    default: '',
    description: 'ID of the mailing list to get stats for',
  },
  {
    displayName: 'Date From',
    name: 'statsByDateFrom',
    type: 'dateTime',
    required: true,
    displayOptions: { show: { resource: ['campaign'], operation: ['getStatsByDate'] } },
    default: '',
    description: 'Start date (YYYY-MM-DD)',
  },
  {
    displayName: 'Date To',
    name: 'statsByDateTo',
    type: 'dateTime',
    required: true,
    displayOptions: { show: { resource: ['campaign'], operation: ['getStatsByDate'] } },
    default: '',
    description: 'End date (YYYY-MM-DD)',
  },
];
