import { INodeProperties } from 'n8n-workflow';

export const templateOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['template'] } },
    options: [
      { name: 'Create', value: 'create', description: 'Create a new email template', action: 'Create a template' },
      { name: 'Duplicate', value: 'duplicate', description: 'Duplicate an existing template', action: 'Duplicate a template' },
      { name: 'Get All', value: 'getAll', description: 'Get all email templates', action: 'Get all templates' },
      { name: 'Send Campaign', value: 'sendCampaign', description: 'Create and send a campaign from a template', action: 'Send campaign from template' },
    ],
    default: 'getAll',
  },
];

export const templateFields: INodeProperties[] = [
  {
    displayName: 'Template Name',
    name: 'templateName',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['template'], operation: ['create'] } },
    default: '',
    description: 'Internal name for the template',
  },
  {
    displayName: 'HTML Content',
    name: 'htmlContent',
    type: 'string',
    required: true,
    typeOptions: { rows: 5 },
    displayOptions: { show: { resource: ['template'], operation: ['create'] } },
    default: '',
    description: 'HTML body of the template. Must include *|UNSUBSCRIBE_URL|* placeholder.',
  },
  {
    displayName: 'Subject',
    name: 'subject',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['template'], operation: ['create'] } },
    default: '',
    description: 'Default subject line for campaigns using this template',
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    displayOptions: { show: { resource: ['template'], operation: ['create'] } },
    default: {},
    options: [
      { displayName: 'Custom Category', name: 'custom_category', type: 'string', default: '', description: 'Category label for organising templates' },
    ],
  },
  {
    displayName: 'New Template Name',
    name: 'newTemplateName',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['template'], operation: ['duplicate'] } },
    default: '',
    description: 'Name for the duplicated template',
  },
  {
    displayName: 'Origin Template ID',
    name: 'originTemplateId',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['template'], operation: ['duplicate'] } },
    default: '',
    description: 'ID of the template to duplicate',
  },
  {
    displayName: 'Campaign Name',
    name: 'templateCampaignName',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['template'], operation: ['sendCampaign'] } },
    default: '',
    description: 'Internal name for the campaign',
  },
  {
    displayName: 'Subject',
    name: 'templateCampaignSubject',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['template'], operation: ['sendCampaign'] } },
    default: '',
    description: 'Email subject line',
  },
  {
    displayName: 'Template ID',
    name: 'templateId',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['template'], operation: ['sendCampaign'] } },
    default: '',
    description: 'ID of the template to use for this campaign',
  },
  {
    displayName: 'List IDs',
    name: 'templateListIds',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['template'], operation: ['sendCampaign'] } },
    default: '',
    description: 'Comma-separated list of mailing list IDs to send this campaign to',
  },
  {
    displayName: 'From Email',
    name: 'templateFromEmail',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['template'], operation: ['sendCampaign'] } },
    default: '',
    placeholder: 'sender@example.com',
    description: 'Sender email address',
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFieldsSendCampaign',
    type: 'collection',
    placeholder: 'Add Field',
    displayOptions: { show: { resource: ['template'], operation: ['sendCampaign'] } },
    default: {},
    options: [
      { displayName: 'From Name', name: 'from_name', type: 'string', default: '', description: 'Sender name displayed in the From field' },
      { displayName: 'Schedule Date', name: 'date_send', type: 'dateTime', default: '', description: 'Schedule the campaign for a future date/time' },
      { displayName: 'Use HTTPS', name: 'https', type: 'boolean', default: true, description: 'Whether to use HTTPS for tracking links' },
    ],
  },
];
