import { INodeProperties } from 'n8n-workflow';

export const webhookOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['webhook'] } },
    options: [
      { name: 'Get List Config', value: 'getListConfig', description: 'Get webhook configuration for a mailing list', action: 'Get list webhook config' },
      { name: 'Get SMTP Config', value: 'getSmtpConfig', description: 'Get current SMTP webhook configuration', action: 'Get SMTP webhook config' },
      { name: 'Set List Config', value: 'setListConfig', description: 'Configure webhook for a mailing list', action: 'Set list webhook config' },
      { name: 'Set SMTP Config', value: 'setSmtpConfig', description: 'Configure the SMTP webhook', action: 'Set SMTP webhook config' },
    ],
    default: 'getSmtpConfig',
  },
];

export const webhookFields: INodeProperties[] = [
  {
    displayName: 'Callback URL',
    name: 'smtpCallbackUrl',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['webhook'], operation: ['setSmtpConfig'] } },
    default: '',
    placeholder: 'https://your-server.com/webhook',
    description: 'URL that Acumbamail will POST events to',
  },
  {
    displayName: 'Active',
    name: 'smtpActive',
    type: 'boolean',
    displayOptions: { show: { resource: ['webhook'], operation: ['setSmtpConfig'] } },
    default: true,
    description: 'Whether the SMTP webhook is active',
  },
  {
    displayName: 'Events',
    name: 'smtpEvents',
    type: 'collection',
    placeholder: 'Add Event',
    displayOptions: { show: { resource: ['webhook'], operation: ['setSmtpConfig'] } },
    default: {},
    options: [
      { displayName: 'Click', name: 'click', type: 'boolean', default: false, description: 'Notify on link clicks' },
      { displayName: 'Complain', name: 'complain', type: 'boolean', default: false, description: 'Notify on spam complaints' },
      { displayName: 'Delivered', name: 'delivered', type: 'boolean', default: false, description: 'Notify on successful delivery' },
      { displayName: 'Hard Bounce', name: 'hard_bounce', type: 'boolean', default: false, description: 'Notify on hard bounces' },
      { displayName: 'Opens', name: 'opens', type: 'boolean', default: false, description: 'Notify on email opens' },
      { displayName: 'Soft Bounce', name: 'soft_bounce', type: 'boolean', default: false, description: 'Notify on soft bounces' },
    ],
  },
  {
    displayName: 'List ID',
    name: 'webhookListId',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['webhook'], operation: ['getListConfig', 'setListConfig'] } },
    default: '',
    description: 'ID of the mailing list',
  },
  {
    displayName: 'Callback URL',
    name: 'listCallbackUrl',
    type: 'string',
    required: true,
    displayOptions: { show: { resource: ['webhook'], operation: ['setListConfig'] } },
    default: '',
    placeholder: 'https://your-server.com/webhook',
    description: 'URL that Acumbamail will POST events to',
  },
  {
    displayName: 'Active',
    name: 'listActive',
    type: 'boolean',
    displayOptions: { show: { resource: ['webhook'], operation: ['setListConfig'] } },
    default: true,
    description: 'Whether the list webhook is active',
  },
  {
    displayName: 'Events',
    name: 'listEvents',
    type: 'collection',
    placeholder: 'Add Event',
    displayOptions: { show: { resource: ['webhook'], operation: ['setListConfig'] } },
    default: {},
    options: [
      { displayName: 'Click', name: 'click', type: 'boolean', default: false, description: 'Notify on link clicks' },
      { displayName: 'Complain', name: 'complain', type: 'boolean', default: false, description: 'Notify on spam complaints' },
      { displayName: 'Hard Bounce', name: 'hard_bounce', type: 'boolean', default: false, description: 'Notify on hard bounces' },
      { displayName: 'Opens', name: 'opens', type: 'boolean', default: false, description: 'Notify on email opens' },
      { displayName: 'Soft Bounce', name: 'soft_bounce', type: 'boolean', default: false, description: 'Notify on soft bounces' },
      { displayName: 'Subscribes', name: 'subscribes', type: 'boolean', default: false, description: 'Notify on new subscriptions' },
      { displayName: 'Unsubscribes', name: 'unsubscribes', type: 'boolean', default: false, description: 'Notify on unsubscriptions' },
    ],
  },
];
